// <auto-generated />
namespace Domain.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddHistoryTableFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHistoryTableFix));
        
        string IMigrationMetadata.Id
        {
            get { return "202505111108055_AddHistoryTableFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
